interface MovieDetails {
    Title: string,
    Year: Date,
    Rated: string,
    Released: string,
    RunTime: string,
    Genre: string,
    Director: string,
    Writer: string,
    Actors: string,
    Plot: string,
    Language: string,
    Country: string,
    Awards: string,
    Poster: string,
    MetaScore: number,
    imdbRating: string,
    imdbVotes: number,
    imdbId: string,
    Type: string,
    DVD: Date,
    BoxOffice: string,
    Production: string,
    Website: string,
    Response: boolean
}